import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Youtube Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://logos-world.net/wp-content/uploads/2020/04/YouTube-Emblem.png" />
      </Head>


      <div className="container">
            <h3 className={styles.animatecharcter}>Youtube Video Downloader</h3>
      </div> 
      <div>
        <label className={styles.search}>Search Here, </label>
        <input className={styles.inputBox} type="text" placeholder='Paste The URL'></input>
        <input className={styles.submit} type="submit"></input>
      </div>
      

     
    </div>
  )
}
